version: '3'
#AppleSilicon_M1チップを使用した新しいMacの場合、
#platformに「linux/amd64」を指定する必要がある。
#対象のPCの場合はplatformのコメントアウトを外す。

services:
  web:
    platform: linux/amd64
    container_name: Vue_web
    # ./web/Dockerfile でイメージをビルド
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    # db 起動後に web を起動
    depends_on:
      - db
    # 80 番ポートを割り当て
    ports:
      - '80:80'
      - '5173:5173'
    # ローカル の ./ フォルダを
    # コンテナの /var/www/html にマウント
    volumes:
      - './html:/var/www/html'
    networks:
      - vue

  # MySQL
  db:
    #platform: linux/amd64
    container_name: vue_db
    image: mysql:8.0
    volumes:
      - './docker/db:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_DATABASE: vue
      MYSQL_USER: vue-user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - vue

  # phpMyAdmin
  pma:
    container_name: vue_pma
    image: phpmyadmin/phpmyadmin:5.0
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      PMA_HOST: vue_db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - vue

  redis:
    build: ./docker/redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/data
    networks:
      - vue

  mailcatcher:
    build: ./docker/mailcatcher
    ports:
      - "${MAILCATCHER_PORT}:1080"
    networks:
      - vue
  minio:
    build: ./docker/minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio:/data
    networks:
      - vue

volumes:
  mysql:
  redis:
  minio:
networks:
  vue: